server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    username: root
    password: Root@123
    url: jdbc:mysql://localhost:3306/E-commerceApi


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


